stages:
- stage: Stage1
  jobs:
  - job: Phase_1
    displayName: A
    pool: Hosted VS2017
    steps:
    - powershell: Write-Host 'Hellow World'
      displayName: 'PowerShell Script'
  - job: Phase_2
    displayName: Agentless
    pool: server
    steps:
    - task: Delay@1
      inputs:
        delayForMinutes: '1'
  - job: Phase_3
    displayName: C
    condition: succeeded()
    dependsOn: 
    - Phase_1
    - Phase_2
    pool : Hosted VS2017
    steps:
    - powershell: Write-Host "Ths is Phase3" 
      displayName: 'PowerShell Script'
